export const EnvKeys = {
  DATABASE_URL: "DATABASE_URL",
  JWT_SECRET: "JWT_SECRET",
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET",
  PORT: "PORT",
} as const;
