export const EnvKeys = {
  DATABASE_URL: "DATABASE_URL",
  ACCESS_SECRET: "ACCESS_SECRET",
  REFRESH_SECRET: "REFRESH_SECRET",
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET",
  PORT: "PORT",
} as const;
